apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: whoami-lb
  namespace: default
spec:
  host: whoami.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

---
