apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-load-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpu-load-app
  template:
    metadata:
      labels:
        app: cpu-load-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: app
        image: node0:5000/cpu-load-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-load-svc
spec:
  selector:
    app: cpu-load-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cpu-load-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu-load-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50