# locust-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
data:
  locustfile.py: |
    from locust import HttpUser, task, between
    import time
    
    class TestUser(HttpUser):
        wait_time = between(1, 3)
        
        @task
        def test_endpoint(self):
            self.client.get("/api/compute")  # CPU密集型endpoint